#!/bin/bash

$SYNC_TO = $1

for THEME_FOLDER in 'lsecities-urbanage' 'twentyeleven-child-lsecities' 'twentyeleven-child-lsecities-urbanage'
do
	rsync -n -v -a --delete $theme_folder $SYNC_TO/$THEME_FOLDER
done
