#!/bin/bash

$SYNC_TO = $1

for $theme_folder in 'lsecities-urbanage' 'twentyeleven-child-lsecities' 'twentyeleven-child-lsecities-urbanage'
do
	rsync -n -v -a --delete $theme_folder $SYNC_TO/$theme_folder
done
