#!/bin/bash

SYNC_TO=$1

for THEME_FOLDER in 'lsecities-urbanage' 'twentyeleven-child-lsecities' 'twentyeleven-child-lsecities-urbanage'
do
	CMD="rsync -v -a --delete $THEME_FOLDER $SYNC_TO/"
	echo $CMD
	$CMD
done
